// Typelizer digest b33ecaea81da1086b49cd203ca04207e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import { buildUrl } from './runtime'

export default {
  /** GET / */
  index: (options) => ({
    url: buildUrl('/', {}, options),
    method: 'get',
  }),
}
