// Typelizer digest d78e4c9f45b3d12b2bcdcec15819f8e6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as home } from './HomeController'

import _home from './HomeController'

export const root = _home.index
